// SPDX-License-Identifier: MIT
pragma solidity ^0.8.30;

import "@openzeppelin/contracts/token/ERC20/extensions/ERC4626.sol";
import "@openzeppelin/contracts/access/Ownable.sol";
import "@openzeppelin/contracts/token/ERC20/IERC20.sol";
import "@openzeppelin/contracts/token/ERC20/utils/SafeERC20.sol";
import "./IStrategy.sol";

/**
 * @title PulseVault
 * @notice Ultra-efficient real-time yield optimizer for OPN Chain.
 *
 * Key innovation for OPN:
 * - 1-second block times + extremely low gas (7 gwei) make frequent harvesting (every few seconds/minutes) profitable.
 * - On slower/expensive chains this would lose money to gas. Here it captures significantly more yield.
 * - Permissionless harvest/rebalance with keeper tips.
 * - Real-time on-chain totalAssets() that reflects continuous per-second accrual.
 *
 * Users deposit the underlying (tOPN or future real asset), receive pOPN shares.
 * Yield is generated by allocating to strategies and harvesting often.
 */
contract PulseVault is ERC4626, Ownable {
    using SafeERC20 for IERC20;

    IStrategy[] public strategies;
    uint256[] public allocations; // basis points (10000 = 100%)

    uint256 public totalHarvests;
    uint256 public lastHarvestTime;

    // Small performance fee (1%) taken on harvest for the vault/treasury (demo)
    uint256 public constant PERFORMANCE_FEE_BPS = 100;

    event Rebalanced(uint256 totalStrategies, uint256 timestamp);
    event Harvested(uint256 totalProfit, uint256 keeperTipsPaid, uint256 fee, address indexed caller);
    event StrategyAdded(address indexed strategy, uint256 allocationBps);
    event AllocationUpdated(uint256[] newAllocations);

    constructor(
        IERC20 _asset,
        string memory _name,
        string memory _symbol
    ) ERC4626(_asset) ERC20(_name, _symbol) Ownable(msg.sender) {
        lastHarvestTime = block.timestamp;
    }

    // ==================== STRATEGY MANAGEMENT ====================

    function addStrategy(address strategy, uint256 allocationBps) external onlyOwner {
        require(strategy != address(0), "Invalid strategy");
        require(allocationBps <= 10000, "Allocation too high");

        strategies.push(IStrategy(strategy));
        allocations.push(allocationBps);

        emit StrategyAdded(strategy, allocationBps);
    }

    function setAllocations(uint256[] calldata newAllocations) external onlyOwner {
        require(newAllocations.length == strategies.length, "Length mismatch");
        uint256 total;
        for (uint256 i = 0; i < newAllocations.length; i++) {
            total += newAllocations[i];
        }
        require(total == 10000, "Must sum to 100%");

        allocations = newAllocations;
        emit AllocationUpdated(newAllocations);
    }

    // ==================== CORE YIELD LOGIC ====================

    /**
     * @notice Total assets = idle balance in vault + all strategy assets.
     * This is what makes the share price increase in real-time as strategies accrue.
     */
    function totalAssets() public view override returns (uint256) {
        uint256 assets = IERC20(asset()).balanceOf(address(this));
        for (uint256 i = 0; i < strategies.length; i++) {
            assets += strategies[i].totalAssets();
        }
        return assets;
    }

    /**
     * @notice The magic function. Anyone can call this.
     * On OPN Chain this is extremely cheap, so calling it every 30-60 seconds is viable and captures yield that would otherwise be left on the table.
     */
    function harvestAndRebalance() public {
        _doHarvestAndRebalance();
    }

    /// @notice Convenience for users / bots: just harvest without full rebalance comment
    function harvest() external {
        _doHarvestAndRebalance();
    }

    /**
     * @notice Optional manual rebalance that can move funds between strategies
     * according to current target allocations.
     * Call after harvest to keep capital deployed optimally.
     */
    function rebalance() external {
        // For MVP: we simply harvest (which compounds). 
        // A full version would calculate current deployed vs target and move.
        // This function exists so the UI can clearly show "Rebalance" action.
        _doHarvestAndRebalance();
        emit Rebalanced(strategies.length, block.timestamp);
    }

    function _doHarvestAndRebalance() internal {
        uint256 totalProfit = 0;
        uint256 totalTips = 0;

        for (uint256 i = 0; i < strategies.length; i++) {
            IStrategy strat = strategies[i];
            uint256 before = strat.totalAssets();

            uint256 profit = strat.harvest();

            if (profit > 0) {
                totalProfit += profit;

                // Keeper tip is already handled inside strategy (emitted)
                // Here we could pull if the strat sent tokens, but in our mocks profit is accounting-based.
            }

            // Simple rebalance idea: after harvest we could move capital, but for clarity we keep allocation static
            // In a more advanced version we would compare recent yields and shift.
        }

        totalHarvests += 1;
        lastHarvestTime = block.timestamp;

        // Take small performance fee to vault (increases TVL for all, or can be sent to treasury)
        uint256 fee = (totalProfit * PERFORMANCE_FEE_BPS) / 10000;
        if (fee > 0) {
            // In this mock the fee just stays in the "accrued" of strategies or idle.
            // Real version would withdraw fee to a treasury address.
        }

        emit Harvested(totalProfit, totalTips, fee, msg.sender);
        emit Rebalanced(strategies.length, block.timestamp);
    }

    // ==================== DEPOSIT / WITHDRAW OVERRIDES (ERC4626) ====================

    /**
     * @dev We override to optionally auto-allocate new deposits across strategies.
     * For simplicity in this version we keep most capital "idle" until first harvest/rebalance
     * or we can push a portion immediately. Keeping it simple and gas efficient.
     */
    function _deposit(address caller, address receiver, uint256 assets, uint256 shares) internal override {
        super._deposit(caller, receiver, assets, shares);

        // Immediately deploy a portion of new capital for better UX and to demonstrate allocation.
        // The rest can stay idle until rebalance (cheap on OPN).
        _deployIdleCapital();
    }

    /// @notice Anyone can call this to move idle vault balance into the strategies according to allocation targets.
    /// This + harvest is the "real-time" action that is only viable because of OPN Chain's speed and cost.
    function deployIdleCapital() external {
        _deployIdleCapital();
    }

    function _deployIdleCapital() internal {
        if (strategies.length == 0) return;

        address _asset = asset();
        uint256 idle = IERC20(_asset).balanceOf(address(this));
        if (idle == 0) return;

        for (uint256 i = 0; i < strategies.length; i++) {
            uint256 bps = allocations[i];
            if (bps == 0) continue;
            uint256 toStrat = (idle * bps) / 10000;
            if (toStrat > 0) {
                IERC20(_asset).safeTransfer(address(strategies[i]), toStrat);
                strategies[i].deposit(toStrat);
            }
        }
    }

    function _withdraw(
        address caller,
        address receiver,
        address owner,
        uint256 assets,
        uint256 shares
    ) internal override {
        uint256 idle = IERC20(asset()).balanceOf(address(this));

        if (idle < assets) {
            uint256 needed = assets - idle;
            // Pull proportionally from strategies (simplified: from first strategy with assets)
            for (uint256 i = 0; i < strategies.length && needed > 0; i++) {
                uint256 stratAssets = strategies[i].totalAssets();
                if (stratAssets == 0) continue;

                uint256 pull = needed > stratAssets ? stratAssets : needed;
                strategies[i].withdraw(pull);
                needed -= pull;
            }
        }

        super._withdraw(caller, receiver, owner, assets, shares);
    }

    // ==================== VIEW HELPERS FOR FRONTEND (real-time UX) ====================

    function getStrategyCount() external view returns (uint256) {
        return strategies.length;
    }

    function getStrategyInfo(uint256 index) external view returns (
        address strategyAddress,
        uint256 allocationBps,
        uint256 currentAssets
    ) {
        require(index < strategies.length, "Invalid index");
        return (
            address(strategies[index]),
            allocations[index],
            strategies[index].totalAssets()
        );
    }

    function getVaultStats() external view returns (
        uint256 tvl,
        uint256 harvests,
        uint256 lastHarvest,
        uint256 secondsSinceLastHarvest
    ) {
        tvl = totalAssets();
        harvests = totalHarvests;
        lastHarvest = lastHarvestTime;
        secondsSinceLastHarvest = block.timestamp - lastHarvestTime;
    }

    /// @notice Estimated APY is rough (for UI). Real APY comes from how often people harvest.
    function estimatedAPY() external view returns (uint256) {
        // This is illustrative. Real yield depends on harvest frequency + strategy rates.
        // On OPN the effective APY is higher because of frequent compounding.
        if (strategies.length == 0) return 0;

        uint256 weighted;
        for (uint256 i = 0; i < strategies.length; i++) {
            // We don't expose exact rate from strategy for simplicity.
            // Assume average blended ~12-15% if harvested regularly.
            weighted += allocations[i];
        }
        // Return a placeholder that frontend can enhance with on-chain data + "boost from frequency"
        return 1200; // 12.00% base (frontend will show "real-time boost")
    }
}
